### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by koivunej** [rs-ipfs/rust-ipfs#356]
It's been literally forever since the last release and we've been discussing this internally. Releasing the crates will allow us to jump into making the docs better through docs.rs visibility and hopefully make the project more accessible through that way as well.

Thinking it's probably best not to even attempt at many last minute polish since we still have a lot of work ahead of us.

- [x] update bootstrap list to match latest [go-ipfs bootstrap peers](https://github.com/ipfs/go-ipfs-config/blob/master/bootstrap_peers.go#L17) #387
   - ~needs decision: resolve dnsaddr outside of libp2p, expand it manually or~ just not include /dnsaddr
- [x] use static bootstrap peers instead of [reloading config file](https://github.com/rs-ipfs/rust-ipfs/blob/ffc65c8b5de3390e94864904e11cbc425a3912e7/src/p2p/behaviour.rs#L596-L625) #387
- [x] ipfs-http: listening addresses from compat config file (see #173) #383
- [x] remove default random listening address, listen to no addresses by default (re: #173) #383
- [x] remove ipns insertion and cancellation features from ipfs::Ipfs (they are not implemented) #384
- [x] comment on resolve_ipns that it only supports dnslink was #385 but fused into #384
- [x] move README.md example as an example under `examples/`, stop polluting src/lib.rs docs #391 
- [x] be on a look out for other half-way implemented features and update docs #392 
- [x] crate level ipfs-http documentation (in #392)
- [x] update #6 regarding IPNS progress
- [x] go through remaining examples (removed the ipns one in #384) -- #390
- [x] simplify node creation #345 maybe? in #394
- [x] remove UninitializedIpfs::default, IpfsOptions::default and `src/config.rs` except for bootstrapper list, see [comment](https://github.com/rs-ipfs/rust-ipfs/issues/356#issuecomment-696780366), #393
- [x] ~add add example~, discussed more in deferral #395
- [x] crates.io prep, me as ipfs owner
- [x] ipfs-unixfs changelog, bump ipfs-unixfs to 0.2.0, #396
- [x] ipfs-unixfs tag+publish
- [x] prepare to publish `bitswap/` as ipfs-bitswap 0.1.0 #397 #398 (again)
- [x] tag+publish ipfs-bitswap
- [x] prepare to publish ipfs as 0.2.0 #399
- [x] tag+publish ipfs
- [x] create persistence tracking issue, current state #401
- [x] create [gh release with release notes](https://github.com/rs-ipfs/rust-ipfs/releases/tag/ipfs%40v0.2.0)
- [ ] begin a CHANGELOG for ipfs, update contributing guidelines, PR checklist cc: #171, #400

**Comment by koivunej** [comment]
Updated the list. Expanding thoughts on a few here:

Resolving `/dnsaddr/bootstrap.libp2p.io/p2p/$id` outside of rust-libp2p:
  * this would be recursive query to find the /ip4 or /ip6 by following TXT fields

The `/dnsaddr/bootstrap...` could be manually expanded, but the downside is that the ipfs infra team is likely using the dnsaddr to help them manage the system better, and manually expanding would actively work against their freedom to manage the bootstrap node cluster. Though, even at the moment the cluster includes a single peer which is not on the go-ipfs list, unsure why.

Perhaps the easiest is just to keep the single bootstrapper which has the static known ip address.

Rationale for not reloading the config file: We should be getting away from config file implementation in `ipfs`. While it was necessary in the beginning, library configuration is an application level concern which should be handled by the app. An app can provide which ever kind of nice runtime config reloading or whatnot, however as a library I think `ipfs` should not strive to support any kinds of concrete configuration persistence strategies.

Removal of public ipns functionality: The flatfs based persistent datastore has never supported ipns nor have ipns records ever been read from the network.

**Comment by koivunej** [comment]
Edited the list again, adding the README.md example moving and simplification through that.

I also added the src/config.rs removal along with its only dependency `IpfsOptions::default()`. I've wanted to do this for a while know but forgot about it until it was actually needed in bootstrap_restore. I don't think libraries should ship with config file handling as the topic is too complicated. If some apps want to do bidirectional config file handling they are welcome to do that, but it shouldn't be the goal of `ipfs` as we already have quite a lot of on our hands.

**Comment by koivunej** [comment]
Edited list once again, post starting to merge #392 and I had forgotten about #345, added it as a maybe, linked #393.
