### ISSUE TITLE
Persistence tracking issue

### ISSUE THREAD

**Issue by koivunej** [rs-ipfs/rust-ipfs#401]
Lets start tracking the overall "persistence" features and discussion.

- [x] Blocks
- [x] Pins
- [ ] Block garbage collection
- [ ] Providing and reproviding every 12h
- [ ] Architecture and interfacing with the repository

(to be edited)

**Comment by koivunej** [comment]
The current state is that we have *a* filesystem backed block and pin storage. We decided to go with filesystem backed storage as supporting different transactional stores will take a lot of design, and might not be even ideal to try to support different backends, at least in the current design where "repo" is a dependency inside the `src/p2p/behaviour.rs`. We haven't really done much or any discovery, design or attempts at solving this yet. 

One possibility could be to run the repo and libp2p swarm alongside each other, bubbling events up from the behaviour to communicate between the two, and to keep using the "repo" directly from the facade. This would provide a central place to track the spawned tasks, for example at the current `IpfsFuture`.
